remote_theme: pages-themes/cayman@v0.2.0
livereload: true
url: https://www.shahanimedya.com/
title: Shahanı Medya Yayincilik
description: Vizyon sahibi bir medya
lang: tr_TR
locale: tr_TR
collections:
  gallery:
    files: true

social:
  name: Shahanı Medya
  links:
    - https://www.instagram.com/shahanimedya/
    - https://www.facebook.com/profile.php?id=100082866865573

contacts:
  - title: Tel
    name:
    phone: 0242 511 5040
    email: shahanimedya@gmail.com
  - title: Medya sahibi
    name: Can İPEKOĞLU
    phone: 0532 290 4603
    email: shahanisiavash@gmail.com
  - title: Genel Yayın Yönetmeni
    name: Esin İPEKOĞLU
    phone: 0536 633 9017
    email: esin.shahanimedya@gmail.com
  - title: Yapımcı Asistanı
    name: İlayda ÇELİK
    phone: 0532 358 2074
    email: İlayda.shahanimedya@gmail.com


slides:
  - src: /assets/img/b-1.jpg
    id: 1
  - src: /assets/img/b-2.jpg
    id: 2
  - src: /assets/img/b-3.jpg
    id: 3
  - src: /assets/img/b-4.jpg
    id: 4

